### ISSUE TITLE
IOError: Locale path not found.

### ISSUE THREAD

**Issue by SwayingGaze** [rafael1193/spicegui#2]
me@me-Aspire-E5-572G:~$ spicegui
Traceback (most recent call last):
  File "/usr/local/bin/spicegui", line 9, in <module>
    load_entry_point('spicegui==1.0', 'gui_scripts', 'spicegui')()
  File "/usr/local/lib/python2.7/dist-packages/spicegui-1.0-py2.7.egg/spicegui/**init**.py", line 57, in start
    locale_path = get_locale_path()
  File "/usr/local/lib/python2.7/dist-packages/spicegui-1.0-py2.7.egg/spicegui/**init**.py", line 49, in get_locale_path
    raise IOError("Locale path not found.")
IOError: Locale path not found.

**Comment by rafael1193** [comment]
#3 should solve the issue. Could you try the fix?
